// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mymqttmessages.proto

package friendisnear.friendisnear.utilities.mymqttmessages;

public final class ProtobufMessages {
  private ProtobufMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PBMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mymqttmessages.PBMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 source = 1;</code>
     */
    boolean hasSource();
    /**
     * <code>required uint32 source = 1;</code>
     */
    int getSource();

    /**
     * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
     */
    boolean hasLocation();
    /**
     * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
     */
    friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation getLocation();
    /**
     * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
     */
    friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocationOrBuilder getLocationOrBuilder();

    /**
     * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
     */
    boolean hasText();
    /**
     * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
     */
    friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText getText();
    /**
     * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
     */
    friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericTextOrBuilder getTextOrBuilder();

    public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage.MsgtypeCase getMsgtypeCase();
  }
  /**
   * Protobuf type {@code mymqttmessages.PBMessage}
   */
  public  static final class PBMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mymqttmessages.PBMessage)
      PBMessageOrBuilder {
    // Use PBMessage.newBuilder() to construct.
    private PBMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBMessage() {
      source_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PBMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              source_ = input.readUInt32();
              break;
            }
            case 810: {
              friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.Builder subBuilder = null;
              if (msgtypeCase_ == 101) {
                subBuilder = ((friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation) msgtype_).toBuilder();
              }
              msgtype_ =
                  input.readMessage(friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation) msgtype_);
                msgtype_ = subBuilder.buildPartial();
              }
              msgtypeCase_ = 101;
              break;
            }
            case 818: {
              friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.Builder subBuilder = null;
              if (msgtypeCase_ == 102) {
                subBuilder = ((friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText) msgtype_).toBuilder();
              }
              msgtype_ =
                  input.readMessage(friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText) msgtype_);
                msgtype_ = subBuilder.buildPartial();
              }
              msgtypeCase_ = 102;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage.class, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage.Builder.class);
    }

    private int bitField0_;
    private int msgtypeCase_ = 0;
    private java.lang.Object msgtype_;
    public enum MsgtypeCase
        implements com.google.protobuf.Internal.EnumLite {
      LOCATION(101),
      TEXT(102),
      MSGTYPE_NOT_SET(0);
      private final int value;
      private MsgtypeCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgtypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgtypeCase forNumber(int value) {
        switch (value) {
          case 101: return LOCATION;
          case 102: return TEXT;
          case 0: return MSGTYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgtypeCase
    getMsgtypeCase() {
      return MsgtypeCase.forNumber(
          msgtypeCase_);
    }

    public static final int SOURCE_FIELD_NUMBER = 1;
    private int source_;
    /**
     * <code>required uint32 source = 1;</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 source = 1;</code>
     */
    public int getSource() {
      return source_;
    }

    public static final int LOCATION_FIELD_NUMBER = 101;
    /**
     * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
     */
    public boolean hasLocation() {
      return msgtypeCase_ == 101;
    }
    /**
     * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
     */
    public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation getLocation() {
      if (msgtypeCase_ == 101) {
         return (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation) msgtype_;
      }
      return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.getDefaultInstance();
    }
    /**
     * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
     */
    public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocationOrBuilder getLocationOrBuilder() {
      if (msgtypeCase_ == 101) {
         return (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation) msgtype_;
      }
      return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.getDefaultInstance();
    }

    public static final int TEXT_FIELD_NUMBER = 102;
    /**
     * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
     */
    public boolean hasText() {
      return msgtypeCase_ == 102;
    }
    /**
     * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
     */
    public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText getText() {
      if (msgtypeCase_ == 102) {
         return (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText) msgtype_;
      }
      return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.getDefaultInstance();
    }
    /**
     * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
     */
    public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericTextOrBuilder getTextOrBuilder() {
      if (msgtypeCase_ == 102) {
         return (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText) msgtype_;
      }
      return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasLocation()) {
        if (!getLocation().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasText()) {
        if (!getText().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, source_);
      }
      if (msgtypeCase_ == 101) {
        output.writeMessage(101, (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation) msgtype_);
      }
      if (msgtypeCase_ == 102) {
        output.writeMessage(102, (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText) msgtype_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, source_);
      }
      if (msgtypeCase_ == 101) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(101, (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation) msgtype_);
      }
      if (msgtypeCase_ == 102) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(102, (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText) msgtype_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage)) {
        return super.equals(obj);
      }
      friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage other = (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage) obj;

      boolean result = true;
      result = result && (hasSource() == other.hasSource());
      if (hasSource()) {
        result = result && (getSource()
            == other.getSource());
      }
      result = result && getMsgtypeCase().equals(
          other.getMsgtypeCase());
      if (!result) return false;
      switch (msgtypeCase_) {
        case 101:
          result = result && getLocation()
              .equals(other.getLocation());
          break;
        case 102:
          result = result && getText()
              .equals(other.getText());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSource()) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSource();
      }
      switch (msgtypeCase_) {
        case 101:
          hash = (37 * hash) + LOCATION_FIELD_NUMBER;
          hash = (53 * hash) + getLocation().hashCode();
          break;
        case 102:
          hash = (37 * hash) + TEXT_FIELD_NUMBER;
          hash = (53 * hash) + getText().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mymqttmessages.PBMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mymqttmessages.PBMessage)
        friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage.class, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage.Builder.class);
      }

      // Construct using friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        source_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgtypeCase_ = 0;
        msgtype_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBMessage_descriptor;
      }

      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage getDefaultInstanceForType() {
        return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage.getDefaultInstance();
      }

      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage build() {
        friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage buildPartial() {
        friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage result = new friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.source_ = source_;
        if (msgtypeCase_ == 101) {
          if (locationBuilder_ == null) {
            result.msgtype_ = msgtype_;
          } else {
            result.msgtype_ = locationBuilder_.build();
          }
        }
        if (msgtypeCase_ == 102) {
          if (textBuilder_ == null) {
            result.msgtype_ = msgtype_;
          } else {
            result.msgtype_ = textBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.msgtypeCase_ = msgtypeCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage) {
          return mergeFrom((friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage other) {
        if (other == friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage.getDefaultInstance()) return this;
        if (other.hasSource()) {
          setSource(other.getSource());
        }
        switch (other.getMsgtypeCase()) {
          case LOCATION: {
            mergeLocation(other.getLocation());
            break;
          }
          case TEXT: {
            mergeText(other.getText());
            break;
          }
          case MSGTYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSource()) {
          return false;
        }
        if (hasLocation()) {
          if (!getLocation().isInitialized()) {
            return false;
          }
        }
        if (hasText()) {
          if (!getText().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgtypeCase_ = 0;
      private java.lang.Object msgtype_;
      public MsgtypeCase
          getMsgtypeCase() {
        return MsgtypeCase.forNumber(
            msgtypeCase_);
      }

      public Builder clearMsgtype() {
        msgtypeCase_ = 0;
        msgtype_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int source_ ;
      /**
       * <code>required uint32 source = 1;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 source = 1;</code>
       */
      public int getSource() {
        return source_;
      }
      /**
       * <code>required uint32 source = 1;</code>
       */
      public Builder setSource(int value) {
        bitField0_ |= 0x00000001;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 source = 1;</code>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000001);
        source_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.Builder, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocationOrBuilder> locationBuilder_;
      /**
       * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
       */
      public boolean hasLocation() {
        return msgtypeCase_ == 101;
      }
      /**
       * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
       */
      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation getLocation() {
        if (locationBuilder_ == null) {
          if (msgtypeCase_ == 101) {
            return (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation) msgtype_;
          }
          return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.getDefaultInstance();
        } else {
          if (msgtypeCase_ == 101) {
            return locationBuilder_.getMessage();
          }
          return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.getDefaultInstance();
        }
      }
      /**
       * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
       */
      public Builder setLocation(friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgtype_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }
        msgtypeCase_ = 101;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
       */
      public Builder setLocation(
          friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.Builder builderForValue) {
        if (locationBuilder_ == null) {
          msgtype_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }
        msgtypeCase_ = 101;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
       */
      public Builder mergeLocation(friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation value) {
        if (locationBuilder_ == null) {
          if (msgtypeCase_ == 101 &&
              msgtype_ != friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.getDefaultInstance()) {
            msgtype_ = friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.newBuilder((friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation) msgtype_)
                .mergeFrom(value).buildPartial();
          } else {
            msgtype_ = value;
          }
          onChanged();
        } else {
          if (msgtypeCase_ == 101) {
            locationBuilder_.mergeFrom(value);
          }
          locationBuilder_.setMessage(value);
        }
        msgtypeCase_ = 101;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          if (msgtypeCase_ == 101) {
            msgtypeCase_ = 0;
            msgtype_ = null;
            onChanged();
          }
        } else {
          if (msgtypeCase_ == 101) {
            msgtypeCase_ = 0;
            msgtype_ = null;
          }
          locationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
       */
      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.Builder getLocationBuilder() {
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
       */
      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocationOrBuilder getLocationOrBuilder() {
        if ((msgtypeCase_ == 101) && (locationBuilder_ != null)) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          if (msgtypeCase_ == 101) {
            return (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation) msgtype_;
          }
          return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.getDefaultInstance();
        }
      }
      /**
       * <code>optional .mymqttmessages.PBGenericLocation location = 101;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.Builder, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocationOrBuilder>
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          if (!(msgtypeCase_ == 101)) {
            msgtype_ = friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.getDefaultInstance();
          }
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.Builder, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocationOrBuilder>(
                  (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation) msgtype_,
                  getParentForChildren(),
                  isClean());
          msgtype_ = null;
        }
        msgtypeCase_ = 101;
        onChanged();;
        return locationBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.Builder, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericTextOrBuilder> textBuilder_;
      /**
       * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
       */
      public boolean hasText() {
        return msgtypeCase_ == 102;
      }
      /**
       * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
       */
      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText getText() {
        if (textBuilder_ == null) {
          if (msgtypeCase_ == 102) {
            return (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText) msgtype_;
          }
          return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.getDefaultInstance();
        } else {
          if (msgtypeCase_ == 102) {
            return textBuilder_.getMessage();
          }
          return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.getDefaultInstance();
        }
      }
      /**
       * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
       */
      public Builder setText(friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText value) {
        if (textBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgtype_ = value;
          onChanged();
        } else {
          textBuilder_.setMessage(value);
        }
        msgtypeCase_ = 102;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
       */
      public Builder setText(
          friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.Builder builderForValue) {
        if (textBuilder_ == null) {
          msgtype_ = builderForValue.build();
          onChanged();
        } else {
          textBuilder_.setMessage(builderForValue.build());
        }
        msgtypeCase_ = 102;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
       */
      public Builder mergeText(friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText value) {
        if (textBuilder_ == null) {
          if (msgtypeCase_ == 102 &&
              msgtype_ != friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.getDefaultInstance()) {
            msgtype_ = friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.newBuilder((friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText) msgtype_)
                .mergeFrom(value).buildPartial();
          } else {
            msgtype_ = value;
          }
          onChanged();
        } else {
          if (msgtypeCase_ == 102) {
            textBuilder_.mergeFrom(value);
          }
          textBuilder_.setMessage(value);
        }
        msgtypeCase_ = 102;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
       */
      public Builder clearText() {
        if (textBuilder_ == null) {
          if (msgtypeCase_ == 102) {
            msgtypeCase_ = 0;
            msgtype_ = null;
            onChanged();
          }
        } else {
          if (msgtypeCase_ == 102) {
            msgtypeCase_ = 0;
            msgtype_ = null;
          }
          textBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
       */
      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.Builder getTextBuilder() {
        return getTextFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
       */
      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericTextOrBuilder getTextOrBuilder() {
        if ((msgtypeCase_ == 102) && (textBuilder_ != null)) {
          return textBuilder_.getMessageOrBuilder();
        } else {
          if (msgtypeCase_ == 102) {
            return (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText) msgtype_;
          }
          return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.getDefaultInstance();
        }
      }
      /**
       * <code>optional .mymqttmessages.PBGenericText text = 102;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.Builder, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericTextOrBuilder>
          getTextFieldBuilder() {
        if (textBuilder_ == null) {
          if (!(msgtypeCase_ == 102)) {
            msgtype_ = friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.getDefaultInstance();
          }
          textBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.Builder, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericTextOrBuilder>(
                  (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText) msgtype_,
                  getParentForChildren(),
                  isClean());
          msgtype_ = null;
        }
        msgtypeCase_ = 102;
        onChanged();;
        return textBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mymqttmessages.PBMessage)
    }

    // @@protoc_insertion_point(class_scope:mymqttmessages.PBMessage)
    private static final friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage();
    }

    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PBMessage>
        PARSER = new com.google.protobuf.AbstractParser<PBMessage>() {
      public PBMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBMessage> getParserForType() {
      return PARSER;
    }

    public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PBGenericLocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mymqttmessages.PBGenericLocation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 time = 1;</code>
     */
    boolean hasTime();
    /**
     * <code>required int64 time = 1;</code>
     */
    long getTime();

    /**
     * <code>required double latidude = 2;</code>
     */
    boolean hasLatidude();
    /**
     * <code>required double latidude = 2;</code>
     */
    double getLatidude();

    /**
     * <code>required double longitude = 3;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 3;</code>
     */
    double getLongitude();

    /**
     * <code>required float speed = 4;</code>
     */
    boolean hasSpeed();
    /**
     * <code>required float speed = 4;</code>
     */
    float getSpeed();

    /**
     * <code>required bool avaliable = 5;</code>
     */
    boolean hasAvaliable();
    /**
     * <code>required bool avaliable = 5;</code>
     */
    boolean getAvaliable();
  }
  /**
   * Protobuf type {@code mymqttmessages.PBGenericLocation}
   */
  public  static final class PBGenericLocation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mymqttmessages.PBGenericLocation)
      PBGenericLocationOrBuilder {
    // Use PBGenericLocation.newBuilder() to construct.
    private PBGenericLocation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBGenericLocation() {
      time_ = 0L;
      latidude_ = 0D;
      longitude_ = 0D;
      speed_ = 0F;
      avaliable_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PBGenericLocation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readInt64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              latidude_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              longitude_ = input.readDouble();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              speed_ = input.readFloat();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              avaliable_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBGenericLocation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBGenericLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.class, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.Builder.class);
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>required int64 time = 1;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int LATIDUDE_FIELD_NUMBER = 2;
    private double latidude_;
    /**
     * <code>required double latidude = 2;</code>
     */
    public boolean hasLatidude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double latidude = 2;</code>
     */
    public double getLatidude() {
      return latidude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 3;
    private double longitude_;
    /**
     * <code>required double longitude = 3;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double longitude = 3;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int SPEED_FIELD_NUMBER = 4;
    private float speed_;
    /**
     * <code>required float speed = 4;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float speed = 4;</code>
     */
    public float getSpeed() {
      return speed_;
    }

    public static final int AVALIABLE_FIELD_NUMBER = 5;
    private boolean avaliable_;
    /**
     * <code>required bool avaliable = 5;</code>
     */
    public boolean hasAvaliable() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool avaliable = 5;</code>
     */
    public boolean getAvaliable() {
      return avaliable_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatidude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAvaliable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, latidude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, longitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, speed_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, avaliable_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, latidude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, longitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, speed_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, avaliable_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation)) {
        return super.equals(obj);
      }
      friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation other = (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation) obj;

      boolean result = true;
      result = result && (hasTime() == other.hasTime());
      if (hasTime()) {
        result = result && (getTime()
            == other.getTime());
      }
      result = result && (hasLatidude() == other.hasLatidude());
      if (hasLatidude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLatidude())
            == java.lang.Double.doubleToLongBits(
                other.getLatidude()));
      }
      result = result && (hasLongitude() == other.hasLongitude());
      if (hasLongitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLongitude())
            == java.lang.Double.doubleToLongBits(
                other.getLongitude()));
      }
      result = result && (hasSpeed() == other.hasSpeed());
      if (hasSpeed()) {
        result = result && (
            java.lang.Float.floatToIntBits(getSpeed())
            == java.lang.Float.floatToIntBits(
                other.getSpeed()));
      }
      result = result && (hasAvaliable() == other.hasAvaliable());
      if (hasAvaliable()) {
        result = result && (getAvaliable()
            == other.getAvaliable());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTime());
      }
      if (hasLatidude()) {
        hash = (37 * hash) + LATIDUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLatidude()));
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLongitude()));
      }
      if (hasSpeed()) {
        hash = (37 * hash) + SPEED_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getSpeed());
      }
      if (hasAvaliable()) {
        hash = (37 * hash) + AVALIABLE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getAvaliable());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mymqttmessages.PBGenericLocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mymqttmessages.PBGenericLocation)
        friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBGenericLocation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBGenericLocation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.class, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.Builder.class);
      }

      // Construct using friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        latidude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        speed_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        avaliable_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBGenericLocation_descriptor;
      }

      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation getDefaultInstanceForType() {
        return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.getDefaultInstance();
      }

      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation build() {
        friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation buildPartial() {
        friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation result = new friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.latidude_ = latidude_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.avaliable_ = avaliable_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation) {
          return mergeFrom((friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation other) {
        if (other == friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasLatidude()) {
          setLatidude(other.getLatidude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasAvaliable()) {
          setAvaliable(other.getAvaliable());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTime()) {
          return false;
        }
        if (!hasLatidude()) {
          return false;
        }
        if (!hasLongitude()) {
          return false;
        }
        if (!hasSpeed()) {
          return false;
        }
        if (!hasAvaliable()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long time_ ;
      /**
       * <code>required int64 time = 1;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 time = 1;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>required int64 time = 1;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 time = 1;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        onChanged();
        return this;
      }

      private double latidude_ ;
      /**
       * <code>required double latidude = 2;</code>
       */
      public boolean hasLatidude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double latidude = 2;</code>
       */
      public double getLatidude() {
        return latidude_;
      }
      /**
       * <code>required double latidude = 2;</code>
       */
      public Builder setLatidude(double value) {
        bitField0_ |= 0x00000002;
        latidude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double latidude = 2;</code>
       */
      public Builder clearLatidude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        latidude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>required double longitude = 3;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double longitude = 3;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 3;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000004;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 3;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private float speed_ ;
      /**
       * <code>required float speed = 4;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float speed = 4;</code>
       */
      public float getSpeed() {
        return speed_;
      }
      /**
       * <code>required float speed = 4;</code>
       */
      public Builder setSpeed(float value) {
        bitField0_ |= 0x00000008;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float speed = 4;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        speed_ = 0F;
        onChanged();
        return this;
      }

      private boolean avaliable_ ;
      /**
       * <code>required bool avaliable = 5;</code>
       */
      public boolean hasAvaliable() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bool avaliable = 5;</code>
       */
      public boolean getAvaliable() {
        return avaliable_;
      }
      /**
       * <code>required bool avaliable = 5;</code>
       */
      public Builder setAvaliable(boolean value) {
        bitField0_ |= 0x00000010;
        avaliable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool avaliable = 5;</code>
       */
      public Builder clearAvaliable() {
        bitField0_ = (bitField0_ & ~0x00000010);
        avaliable_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mymqttmessages.PBGenericLocation)
    }

    // @@protoc_insertion_point(class_scope:mymqttmessages.PBGenericLocation)
    private static final friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation();
    }

    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PBGenericLocation>
        PARSER = new com.google.protobuf.AbstractParser<PBGenericLocation>() {
      public PBGenericLocation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBGenericLocation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBGenericLocation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBGenericLocation> getParserForType() {
      return PARSER;
    }

    public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericLocation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PBGenericTextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mymqttmessages.PBGenericText)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string text = 1;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>required string sender = 2;</code>
     */
    boolean hasSender();
    /**
     * <code>required string sender = 2;</code>
     */
    java.lang.String getSender();
    /**
     * <code>required string sender = 2;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();
  }
  /**
   * Protobuf type {@code mymqttmessages.PBGenericText}
   */
  public  static final class PBGenericText extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mymqttmessages.PBGenericText)
      PBGenericTextOrBuilder {
    // Use PBGenericText.newBuilder() to construct.
    private PBGenericText(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBGenericText() {
      text_ = "";
      sender_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PBGenericText(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              text_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sender_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBGenericText_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBGenericText_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.class, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.Builder.class);
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object text_;
    /**
     * <code>required string text = 1;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_FIELD_NUMBER = 2;
    private volatile java.lang.Object sender_;
    /**
     * <code>required string sender = 2;</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string sender = 2;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sender_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sender = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sender_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sender_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText)) {
        return super.equals(obj);
      }
      friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText other = (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText) obj;

      boolean result = true;
      result = result && (hasText() == other.hasText());
      if (hasText()) {
        result = result && getText()
            .equals(other.getText());
      }
      result = result && (hasSender() == other.hasSender());
      if (hasSender()) {
        result = result && getSender()
            .equals(other.getSender());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasText()) {
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
      }
      if (hasSender()) {
        hash = (37 * hash) + SENDER_FIELD_NUMBER;
        hash = (53 * hash) + getSender().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mymqttmessages.PBGenericText}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mymqttmessages.PBGenericText)
        friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericTextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBGenericText_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBGenericText_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.class, friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.Builder.class);
      }

      // Construct using friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sender_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PBGenericText_descriptor;
      }

      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText getDefaultInstanceForType() {
        return friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.getDefaultInstance();
      }

      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText build() {
        friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText buildPartial() {
        friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText result = new friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sender_ = sender_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText) {
          return mergeFrom((friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText other) {
        if (other == friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText.getDefaultInstance()) return this;
        if (other.hasText()) {
          bitField0_ |= 0x00000001;
          text_ = other.text_;
          onChanged();
        }
        if (other.hasSender()) {
          bitField0_ |= 0x00000002;
          sender_ = other.sender_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasText()) {
          return false;
        }
        if (!hasSender()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 1;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sender_ = "";
      /**
       * <code>required string sender = 2;</code>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sender_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sender_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mymqttmessages.PBGenericText)
    }

    // @@protoc_insertion_point(class_scope:mymqttmessages.PBGenericText)
    private static final friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText();
    }

    public static friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PBGenericText>
        PARSER = new com.google.protobuf.AbstractParser<PBGenericText>() {
      public PBGenericText parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBGenericText(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBGenericText> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBGenericText> getParserForType() {
      return PARSER;
    }

    public friendisnear.friendisnear.utilities.mymqttmessages.ProtobufMessages.PBGenericText getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mymqttmessages_PBMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mymqttmessages_PBMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mymqttmessages_PBGenericLocation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mymqttmessages_PBGenericLocation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mymqttmessages_PBGenericText_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mymqttmessages_PBGenericText_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024mymqttmessages.proto\022\016mymqttmessages\"\214" +
      "\001\n\tPBMessage\022\016\n\006source\030\001 \002(\r\0225\n\010location" +
      "\030e \001(\0132!.mymqttmessages.PBGenericLocatio" +
      "nH\000\022-\n\004text\030f \001(\0132\035.mymqttmessages.PBGen" +
      "ericTextH\000B\t\n\007msgtype\"h\n\021PBGenericLocati" +
      "on\022\014\n\004time\030\001 \002(\003\022\020\n\010latidude\030\002 \002(\001\022\021\n\tlo" +
      "ngitude\030\003 \002(\001\022\r\n\005speed\030\004 \002(\002\022\021\n\tavaliabl" +
      "e\030\005 \002(\010\"-\n\rPBGenericText\022\014\n\004text\030\001 \002(\t\022\016" +
      "\n\006sender\030\002 \002(\tB<\n(friendisnear.friendisn" +
      "ear.mymqttmessagesB\020ProtobufMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mymqttmessages_PBMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mymqttmessages_PBMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mymqttmessages_PBMessage_descriptor,
        new java.lang.String[] { "Source", "Location", "Text", "Msgtype", });
    internal_static_mymqttmessages_PBGenericLocation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mymqttmessages_PBGenericLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mymqttmessages_PBGenericLocation_descriptor,
        new java.lang.String[] { "Time", "Latidude", "Longitude", "Speed", "Avaliable", });
    internal_static_mymqttmessages_PBGenericText_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mymqttmessages_PBGenericText_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mymqttmessages_PBGenericText_descriptor,
        new java.lang.String[] { "Text", "Sender", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
